### ISSUE TITLE
Fails to build with latest ubuntu

### ISSUE THREAD

**Issue by vladgolubev** [LogicalSpark/docker-tikaserver#2]
Last time container image was built on docker hub LTS ubuntu version was `14.04 trusty`. 
But now when I try to build an image locally, `FROM ubuntu:latest` references to `16.04 xenial` release.

It fails to build on the step of installing openjdk:

```
Package openjdk-7-jre-headless is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'openjdk-7-jre-headless' has no installation candidate
```

By the way, setting a base image as `FROM ubuntu:14.04` let me build image without any issues.

**Comment by dameikle** [comment]
Thanks for reporting this. The latest Ubuntu now uses either JDK 8 or 9.

Will upgrade this to openjdk-8 for now and consider fixing on Ubuntu releases.
