### ISSUE TITLE
Docker image for 1.23 is broken

### ISSUE THREAD

**Issue by mpdude** [LogicalSpark/docker-tikaserver#22]
When running the 1.23 image, the error `Error: Invalid or corrupt jarfile /tika-server-1.23.jar` is given.

Inspection shows that the `curl` or `wget` for the .jar file `/tika-server-1.23.jar` hit a 403:

```
$ docker run --rm -it --entrypoint /bin/bash  logicalspark/docker-tikaserver:1.23
root@b85e10fc3daa:/# cat /tika-server-1.23.jar
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access this resource.</p>
<hr>
<address>Apache/2.4.29 (Ubuntu) Server at apache.claz.org Port 80</address>
</body></html>
```

**Comment by mpdude** [comment]
Seems this happened with 1.15 and 1.19 before, see #11

**Comment by epugh** [comment]
Since #24 is closed, I wonder if that means this can be closed?

**Comment by mpdude** [comment]
#24 is closed, but I think @dameikle just took the `Dockerfile` I suggested and started a new repo with it under the /apache org at GitHub.

Unless he has rebuilt and re-published the Docker Image, I assume it’s still broken 🤔

**Comment by dameikle** [comment]
No, I've updated here with an updated Dockerfile that take a few of the
different suggestions plus improved fetching logic.

This means the 1.23 image is fixed and with the new download logic, it
shouldn't happen again.

I am planning to sit one night and replay the old tags, so all the images
are updated based on this.

The Apache one is still a work in progress, with Dockerhub access requested
with Infra.

**Comment by mpdude** [comment]
Thanks for the update @dmeikle.

**Comment by mpdude** [comment]
Thanks for the update @dameikle!

**Comment by dameikle** [comment]
Quick update:

It's starting to take shape over at the Apache own repos:
https://hub.docker.com/r/apache/tika

Still got a few more tweaks to do, then will update this one to suggest users start migrating over to that one.
