### ISSUE TITLE
Update docker base to ubuntu:focal

### ISSUE THREAD

**Issue by Dhertz** [LogicalSpark/docker-tikaserver#25]
Upgrade from bionic to focal, as [bionic](http://releases.ubuntu.com/bionic/) is two years old (though is LTS). [Focal](http://releases.ubuntu.com/focal/) is also a LTS version that was released in April. 

This would lead to a bump in the version of tesseract, to their latest release [4.1.1](https://packages.ubuntu.com/focal/tesseract-ocr), rather than the version on bionic, [4.0.0](https://packages.ubuntu.com/bionic/tesseract-ocr). The new version of tesseract includes all fixes and improvements from October 2018 - December 2019.

**Comment by mpdude** [comment]
@dameikle should we still suggest such changes here, or would you prefer if we move over to the Apache repo?

**Comment by dameikle** [comment]
Thanks for this. I've already done a similar update over in the apache repos. Will apply here too.
