### ISSUE TITLE
Add tags from this repo to hub.docker.com

### ISSUE THREAD

**Issue by adamwalz** [LogicalSpark/docker-tikaserver#3]
The only tag on the docker hub is `logicalspark/docker-tikaserver:latest`. Can you please add tags for the other releases from this git repository (1.7, 1.8, 1.9, 1.10, 1.11, 1.12)?

https://hub.docker.com/r/logicalspark/docker-tikaserver

**Comment by adamwalz** [comment]
Would it be possible to add these tags please?

**Comment by peter279k** [comment]
@adamwalz, it seems that the latest stable version tag is `1.20`.

And other tags are available on https://hub.docker.com/r/logicalspark/docker-tikaserver.

I think this issue has been resolved.
