### ISSUE TITLE
Multi-arch build (arm64)

### ISSUE THREAD

**Issue by wazum** [LogicalSpark/docker-tikaserver#34]
Thanks for the Dockerfile, could you add a multi-arch build and also push the tags for arm64?
I tried the Dockerfile with a Linux/Arm64 build and it compiled with no problems.

See https://docs.docker.com/desktop/multi-arch/

**Comment by dameikle** [comment]
Thanks for the suggestion @wazum. I've done a multi-arch build for the 1.28.4 tag and will add them moving forward.
